/**
 * GitHub Actions workflow template and creation
 */

import { readFile, writeFile, fileExists } from "@symbiosis-lab/moss-api";
import { log } from "./utils";

/**
 * GitHub Actions workflow template for deploying to GitHub Pages
 * This is extracted from the original deploy.rs
 */
export const WORKFLOW_TEMPLATE = `# Moss GitHub Pages Deployment
# This workflow deploys your pre-built site from .moss/site/ to GitHub Pages
# Generated by Moss - https://github.com/anthropics/moss

name: Deploy to GitHub Pages

on:
  push:
    branches: [BRANCH_PLACEHOLDER]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .moss/site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
`;

/**
 * Generate the workflow content with the correct branch
 */
export function generateWorkflowContent(branch: string): string {
  return WORKFLOW_TEMPLATE.replace("BRANCH_PLACEHOLDER", branch);
}

/**
 * Create the GitHub Actions workflow file
 */
export async function createWorkflowFile(branch: string): Promise<void> {
  await log("log", "   Creating .github/workflows/moss-deploy.yml...");

  const content = generateWorkflowContent(branch);

  await writeFile(".github/workflows/moss-deploy.yml", content);

  await log("log", "   Workflow file created");
}

/**
 * Update .gitignore to track .moss/site/ while ignoring other .moss/ contents
 */
export async function updateGitignore(): Promise<void> {
  await log("log", "   Updating .gitignore...");

  // Read current gitignore
  let currentContent = "";
  try {
    currentContent = await readFile(".gitignore");
  } catch {
    // File doesn't exist, that's fine
  }

  // Check if already configured
  const hasMossIgnore = currentContent.split("\n").some((line) => {
    const trimmed = line.trim();
    return trimmed === ".moss/" || trimmed === ".moss" || trimmed === "/.moss/" || trimmed === "/.moss";
  });

  const hasSiteException = currentContent.split("\n").some((line) => {
    const trimmed = line.trim();
    return trimmed === "!.moss/site/" || trimmed === "!.moss/site";
  });

  if (hasMossIgnore && hasSiteException) {
    await log("log", "   .gitignore already configured correctly");
    return;
  }

  let newContent = currentContent;

  // Ensure content ends with newline
  if (newContent && !newContent.endsWith("\n")) {
    newContent += "\n";
  }

  // Add .moss/* if not ignoring .moss/
  if (!hasMossIgnore) {
    newContent += "\n# Moss build artifacts (except site/)\n";
    newContent += ".moss/*\n";
  }

  // Add exception for .moss/site/
  if (!hasSiteException) {
    newContent += "!.moss/site/\n";
  }

  await writeFile(".gitignore", newContent);

  await log("log", "   .gitignore updated");
}

/**
 * Check if the workflow file already exists
 */
export async function workflowExists(): Promise<boolean> {
  return fileExists(".github/workflows/moss-deploy.yml");
}
