/**
 * SSG-specific tests for enhance hook functionality
 *
 * Tests that the enhance hook correctly handles HTML generated
 * by different Static Site Generators.
 */

import { describe, it, expect, vi, beforeEach } from "vitest";
import type { Interaction, EnhanceContext } from "../types";

// Mock the moss-api
vi.mock("@symbiosis-lab/moss-api", () => {
  const filesystem = new Map<string, string>();
  return {
    readFile: vi.fn().mockImplementation((path: string) => {
      const content = filesystem.get(path);
      if (!content) throw new Error(`File not found: ${path}`);
      return Promise.resolve(content);
    }),
    writeFile: vi.fn().mockImplementation((path: string, content: string) => {
      filesystem.set(path, content);
      return Promise.resolve();
    }),
    log: vi.fn(),
    __filesystem: filesystem,
  };
});

describe("enhance hook - SSG specific", () => {
  let mockFilesystem: Map<string, string>;

  beforeEach(async () => {
    vi.clearAllMocks();
    vi.resetModules();
    const mod = (await import("@symbiosis-lab/moss-api")) as unknown as {
      __filesystem: Map<string, string>;
    };
    mockFilesystem = mod.__filesystem;
    mockFilesystem.clear();
  });

  const createEnhanceContext = (
    interactions: Interaction[] = [],
    outputDir = "/test/output"
  ): EnhanceContext => ({
    project_path: "/test/project",
    moss_dir: "/test/.moss",
    output_dir: outputDir,
    project_info: {
      content_folders: ["posts"],
      total_files: 1,
    },
    config: {},
    interactions,
  });

  const createInteraction = (
    overrides: Partial<Interaction> = {}
  ): Interaction => ({
    id: `int-${Date.now()}-${Math.random()}`,
    source: "nostr",
    interaction_type: "comment",
    author: {
      name: "Test User",
      identifier: "npub1test",
    },
    content: "Test comment",
    target_url: "posts/test.html",
    ...overrides,
  });

  describe("Hugo", () => {
    it("should inject into Hugo-generated HTML", async () => {
      const hugoHtml = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="generator" content="Hugo 0.123.0">
    <title>Test Post - Hugo Site</title>
</head>
<body>
    <header><nav><a href="/">Home</a></nav></header>
    <main>
        <article class="post">
            <header>
                <h1>Test Post</h1>
                <time datetime="2024-01-15">January 15, 2024</time>
            </header>
            <div class="content">
                <p>This is a test post generated by Hugo.</p>
            </div>
            <footer><span class="tags"><a href="/tags/test/">test</a></span></footer>
        </article>
    </main>
    <footer><p>Hugo Site Footer</p></footer>
</body>
</html>`;
      mockFilesystem.set("/test/output/posts/hugo-post.html", hugoHtml);

      const interactions = [
        createInteraction({ target_url: "posts/hugo-post.html" }),
      ];
      const ctx = createEnhanceContext(interactions);

      const { enhance } = await import("../main");
      const result = await enhance(ctx);

      expect(result.success).toBe(true);

      const modified =
        mockFilesystem.get("/test/output/posts/hugo-post.html") ?? "";
      expect(modified).toContain('id="moss-comments"');

      // Widget should be before </article>
      const widgetIndex = modified.indexOf("moss-comments");
      const articleEndIndex = modified.lastIndexOf("</article>");
      expect(widgetIndex).toBeLessThan(articleEndIndex);
    });
  });

  describe("Hexo", () => {
    it("should inject into Hexo-generated HTML", async () => {
      const hexoHtml = `<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="generator" content="Hexo 6.3.0">
    <title>Test Post | Hexo Blog</title>
</head>
<body>
    <div id="container">
        <header id="header">
            <nav id="main-nav"><a href="/">Home</a></nav>
        </header>
        <div id="content" class="outer">
            <article id="post-test" class="article article-single" itemscope>
                <header class="article-header">
                    <h1 class="article-title">Test Post</h1>
                </header>
                <div class="article-entry" itemprop="articleBody">
                    <p>This is a test post from a Hexo blog.</p>
                </div>
                <footer class="article-footer">
                    <ul class="article-tag-list"><li>hexo</li></ul>
                </footer>
            </article>
        </div>
        <footer id="footer">Powered by Hexo</footer>
    </div>
</body>
</html>`;
      mockFilesystem.set("/test/output/posts/hexo-post.html", hexoHtml);

      const interactions = [
        createInteraction({ target_url: "posts/hexo-post.html" }),
      ];
      const ctx = createEnhanceContext(interactions);

      const { enhance } = await import("../main");
      const result = await enhance(ctx);

      expect(result.success).toBe(true);

      const modified =
        mockFilesystem.get("/test/output/posts/hexo-post.html") ?? "";
      expect(modified).toContain('id="moss-comments"');
    });
  });

  describe("Astro", () => {
    it("should inject into Astro-generated HTML with data-astro attributes", async () => {
      const astroHtml = `<!DOCTYPE html>
<html lang="en" data-astro-cid-sckkx6r4>
<head>
    <meta charset="UTF-8">
    <title>Test Post</title>
</head>
<body data-astro-cid-sckkx6r4>
    <nav data-astro-cid-sckkx6r4><a href="/">Home</a></nav>
    <main data-astro-cid-sckkx6r4>
        <article data-astro-cid-j7pv25f6>
            <header data-astro-cid-j7pv25f6>
                <h1 data-astro-cid-j7pv25f6>Test Post</h1>
            </header>
            <section data-astro-cid-j7pv25f6>
                <p>This is a test post from an Astro site.</p>
            </section>
        </article>
    </main>
    <footer data-astro-cid-sckkx6r4>Built with Astro</footer>
</body>
</html>`;
      mockFilesystem.set("/test/output/posts/astro-post.html", astroHtml);

      const interactions = [
        createInteraction({ target_url: "posts/astro-post.html" }),
      ];
      const ctx = createEnhanceContext(interactions);

      const { enhance } = await import("../main");
      const result = await enhance(ctx);

      expect(result.success).toBe(true);

      const modified =
        mockFilesystem.get("/test/output/posts/astro-post.html") ?? "";
      expect(modified).toContain('id="moss-comments"');
    });
  });

  describe("Error handling", () => {
    it("should handle missing target file gracefully", async () => {
      // Don't add any files to the filesystem
      const interactions = [
        createInteraction({ target_url: "posts/missing.html" }),
      ];
      const ctx = createEnhanceContext(interactions);

      const { enhance } = await import("../main");
      const result = await enhance(ctx);

      // Should still return success but log a warning
      expect(result.success).toBe(true);
    });

    it("should continue processing other files if one fails", async () => {
      // Only add the second file
      mockFilesystem.set(
        "/test/output/posts/post2.html",
        "<html><body><article><h1>Post 2</h1></article></body></html>"
      );

      const interactions = [
        createInteraction({ id: "1", target_url: "posts/post1.html" }), // Missing
        createInteraction({ id: "2", target_url: "posts/post2.html" }), // Exists
      ];
      const ctx = createEnhanceContext(interactions);

      const { enhance } = await import("../main");
      const result = await enhance(ctx);

      expect(result.success).toBe(true);

      // post2 should be modified even though post1 failed
      const post2 = mockFilesystem.get("/test/output/posts/post2.html") ?? "";
      expect(post2).toContain('id="moss-comments"');
    });
  });

  describe("Multiple interaction types", () => {
    it("should handle mixed interaction types (comments and likes)", async () => {
      const html =
        "<html><body><article><h1>Test</h1></article></body></html>";
      mockFilesystem.set("/test/output/posts/mixed.html", html);

      const interactions = [
        createInteraction({
          id: "1",
          target_url: "posts/mixed.html",
          interaction_type: "comment",
          content: "Great post!",
        }),
        createInteraction({
          id: "2",
          target_url: "posts/mixed.html",
          interaction_type: "like",
          content: "",
        }),
        createInteraction({
          id: "3",
          target_url: "posts/mixed.html",
          interaction_type: "comment",
          content: "Thanks for sharing",
        }),
      ];
      const ctx = createEnhanceContext(interactions);

      const { enhance } = await import("../main");
      await enhance(ctx);

      const modified = mockFilesystem.get("/test/output/posts/mixed.html") ?? "";

      // Parse the JSON data
      const dataMatch = modified.match(
        /<script[^>]*id="moss-comments-data"[^>]*>([\s\S]*?)<\/script>/
      );
      expect(dataMatch).toBeTruthy();

      const data = JSON.parse(dataMatch![1].trim());
      expect(data.interactions).toHaveLength(3);

      // Check the noscript fallback shows likes count
      expect(modified).toContain("1 like");
    });
  });

  describe("Special characters in content", () => {
    it("should handle Unicode content correctly", async () => {
      const html =
        "<html><body><article><h1>Test</h1></article></body></html>";
      mockFilesystem.set("/test/output/posts/unicode.html", html);

      const interactions = [
        createInteraction({
          target_url: "posts/unicode.html",
          content: "Great post! 中文评论 🎉 日本語",
          author: { name: "用户", identifier: "npub1unicode" },
        }),
      ];
      const ctx = createEnhanceContext(interactions);

      const { enhance } = await import("../main");
      await enhance(ctx);

      const modified =
        mockFilesystem.get("/test/output/posts/unicode.html") ?? "";

      // Unicode should be preserved in JSON
      expect(modified).toContain("中文评论");
      expect(modified).toContain("🎉");
      expect(modified).toContain("日本語");
      expect(modified).toContain("用户");
    });

    it("should escape HTML entities in author names", async () => {
      const html =
        "<html><body><article><h1>Test</h1></article></body></html>";
      mockFilesystem.set("/test/output/posts/entities.html", html);

      const interactions = [
        createInteraction({
          target_url: "posts/entities.html",
          content: "Comment with <b>bold</b>",
          author: { name: "User <script>", identifier: "npub1bad" },
        }),
      ];
      const ctx = createEnhanceContext(interactions);

      const { enhance } = await import("../main");
      await enhance(ctx);

      const modified =
        mockFilesystem.get("/test/output/posts/entities.html") ?? "";

      // In noscript fallback, dangerous chars should be escaped
      const noscriptMatch = modified.match(/<noscript>([\s\S]*?)<\/noscript>/);
      expect(noscriptMatch).toBeTruthy();
      expect(noscriptMatch![1]).toContain("&lt;script&gt;");
      expect(noscriptMatch![1]).not.toContain("<script>");
    });
  });

  describe("Edge case: very long content", () => {
    it("should handle interactions with very long content", async () => {
      const html =
        "<html><body><article><h1>Test</h1></article></body></html>";
      mockFilesystem.set("/test/output/posts/long.html", html);

      const longContent = "A".repeat(10000); // 10KB comment
      const interactions = [
        createInteraction({
          target_url: "posts/long.html",
          content: longContent,
        }),
      ];
      const ctx = createEnhanceContext(interactions);

      const { enhance } = await import("../main");
      const result = await enhance(ctx);

      expect(result.success).toBe(true);

      const modified = mockFilesystem.get("/test/output/posts/long.html") ?? "";
      expect(modified).toContain('id="moss-comments"');
      // Content should be in the JSON
      expect(modified).toContain(longContent);
    });
  });

  describe("Edge case: many interactions", () => {
    it("should handle many interactions for the same page", async () => {
      const html =
        "<html><body><article><h1>Test</h1></article></body></html>";
      mockFilesystem.set("/test/output/posts/many.html", html);

      // Create 100 interactions
      const interactions = Array.from({ length: 100 }, (_, i) =>
        createInteraction({
          id: `interaction-${i}`,
          target_url: "posts/many.html",
          content: `Comment ${i}`,
        })
      );
      const ctx = createEnhanceContext(interactions);

      const { enhance } = await import("../main");
      const result = await enhance(ctx);

      expect(result.success).toBe(true);

      const modified = mockFilesystem.get("/test/output/posts/many.html") ?? "";

      // Parse the JSON data
      const dataMatch = modified.match(
        /<script[^>]*id="moss-comments-data"[^>]*>([\s\S]*?)<\/script>/
      );
      expect(dataMatch).toBeTruthy();

      const data = JSON.parse(dataMatch![1].trim());
      expect(data.interactions).toHaveLength(100);

      // Noscript should only show first 10
      expect(modified).toContain("Comments (100)");
    });
  });
});
