/**
 * Unit tests for workflow.ts pure functions
 *
 * These tests cover the workflow template generation.
 * Functions that call Tauri (createWorkflowFile, etc.) require integration tests.
 */

import { describe, it, expect } from "vitest";
import { WORKFLOW_TEMPLATE, generateWorkflowContent } from "../workflow";

describe("WORKFLOW_TEMPLATE", () => {
  it("contains the branch placeholder", () => {
    expect(WORKFLOW_TEMPLATE).toContain("BRANCH_PLACEHOLDER");
  });

  it("includes required GitHub Actions setup", () => {
    expect(WORKFLOW_TEMPLATE).toContain("actions/checkout@v4");
    expect(WORKFLOW_TEMPLATE).toContain("actions/configure-pages@v4");
    expect(WORKFLOW_TEMPLATE).toContain("actions/upload-pages-artifact@v3");
    expect(WORKFLOW_TEMPLATE).toContain("actions/deploy-pages@v4");
  });

  it("includes correct permissions", () => {
    expect(WORKFLOW_TEMPLATE).toContain("contents: read");
    expect(WORKFLOW_TEMPLATE).toContain("pages: write");
    expect(WORKFLOW_TEMPLATE).toContain("id-token: write");
  });

  it("references .moss/site as the upload path", () => {
    expect(WORKFLOW_TEMPLATE).toContain("path: .moss/site");
  });

  it("includes workflow_dispatch trigger", () => {
    expect(WORKFLOW_TEMPLATE).toContain("workflow_dispatch:");
  });
});

describe("generateWorkflowContent", () => {
  it("replaces placeholder with main branch", () => {
    const result = generateWorkflowContent("main");
    expect(result).toContain("branches: [main]");
    expect(result).not.toContain("BRANCH_PLACEHOLDER");
  });

  it("replaces placeholder with master branch", () => {
    const result = generateWorkflowContent("master");
    expect(result).toContain("branches: [master]");
    expect(result).not.toContain("BRANCH_PLACEHOLDER");
  });

  it("replaces placeholder with custom branch", () => {
    const result = generateWorkflowContent("develop");
    expect(result).toContain("branches: [develop]");
    expect(result).not.toContain("BRANCH_PLACEHOLDER");
  });

  it("generates valid YAML structure", () => {
    const result = generateWorkflowContent("main");

    // Check for valid YAML key structure
    expect(result).toContain("name: Deploy to GitHub Pages");
    expect(result).toContain("on:");
    expect(result).toContain("permissions:");
    expect(result).toContain("jobs:");
    expect(result).toContain("deploy:");
    expect(result).toContain("steps:");
  });

  it("preserves the Moss header comment", () => {
    const result = generateWorkflowContent("main");
    expect(result).toContain("# Moss GitHub Pages Deployment");
    expect(result).toContain("Generated by Moss");
  });
});
